class IngredientImageMapper {
  static final Map<String, String> _imageMap = {
    "151 proof rum": "151_proof_rum",
    "7-up": "7-up",
    "absinthe": "absinthe",
    "absolut citron": "absolut_citron",
    "absolut kurant": "absolut_kurant",
    "absolut peppar": "absolut_peppar",
    "absolut vodka": "absolut_vodka",
    "advocaat": "advocaat",
    "aejo rum": "aejo_rum",
    "aftershock": "aftershock",
    "agave syrup": "agave_syrup",
    "ale": "ale",
    "allspice dram": "allspice_dram",
    "allspice": "allspice",
    "almond flavoring": "almond_flavoring",
    "almond": "almond",
    "amaretto": "amaretto",
    "amaro montenegro": "amaro_montenegro",
    "añejo rum": "añejo_rum",
    "angelica root": "angelica_root",
    "angostura bitters": "angostura_bitters",
    "anis": "anis",
    "anise": "anise",
    "anisette": "anisette",
    "aperol": "aperol",
    "apfelkorn": "apfelkorn",
    "apple brandy": "apple_brandy",
    "apple cider": "apple_cider",
    "apple juice": "apple_juice",
    "apple schnapps": "apple_schnapps",
    "apple": "apple",
    "applejack": "applejack",
    "apricot brandy": "apricot_brandy",
    "apricot nectar": "apricot_nectar",
    "apricot": "apricot",
    "aquavit": "aquavit",
    "arrack": "arrack",
    "asafoetida": "asafoetida",
    "averna": "averna",
    "bacardi limon": "bacardi_limon",
    "bacardi": "bacardi",
    "baileys irish cream": "baileys_irish_cream",
    "banana liqueur": "banana_liqueur",
    "banana rum": "banana_rum",
    "banana syrup": "banana_syrup",
    "banana": "banana",
    "barenjager": "barenjager",
    "basil": "basil",
    "beef stock": "beef_stock",
    "beer": "beer",
    "benedictine": "benedictine",
    "berries": "berries",
    "bitter lemon": "bitter_lemon",
    "bitters": "bitters",
    "black pepper": "black_pepper",
    "black rum": "black_rum",
    "black sambuca": "black_sambuca",
    "blackberries": "blackberries",
    "blackberry brandy": "blackberry_brandy",
    "blackberry schnapps": "blackberry_schnapps",
    "blackcurrant cordial": "blackcurrant_cordial",
    "blackcurrant schnapps": "blackcurrant_schnapps",
    "blackcurrant squash": "blackcurrant_squash",
    "blackstrap rum": "blackstrap_rum",
    "blended scotch": "blended_scotch",
    "blended whiskey": "blended_whiskey",
    "blood orange": "blood_orange",
    "blue curacao": "blue_curacao",
    "blue maui": "blue_maui",
    "blueberries": "blueberries",
    "blueberry schnapps": "blueberry_schnapps",
    "bourbon": "bourbon",
    "brandy": "brandy",
    "brown sugar": "brown_sugar",
    "butter": "butter",
    "butterscotch schnapps": "butterscotch_schnapps",
    "cachaca": "cachaca",
    "calvados": "calvados",
    "campari": "campari",
    "canadian whisky": "canadian_whisky",
    "candy": "candy",
    "cantaloupe": "cantaloupe",
    "caramel coloring": "caramel_coloring",
    "caramel sauce": "caramel_sauce",
    "carbonated soft drink": "carbonated_soft_drink",
    "carbonated water": "carbonated_water",
    "cardamom": "cardamom",
    "carrot": "carrot",
    "cayenne pepper": "cayenne_pepper",
    "celery salt": "celery_salt",
    "celery": "celery",
    "chambord raspberry liqueur": "chambord_raspberry_liqueur",
    "champagne": "champagne",
    "chareau": "chareau",
    "cherries": "cherries",
    "cherry brandy": "cherry_brandy",
    "cherry cola": "cherry_cola",
    "cherry grenadine": "cherry_grenadine",
    "cherry heering": "cherry_heering",
    "cherry juice": "cherry_juice",
    "cherry liqueur": "cherry_liqueur",
    "cherry": "cherry",
    "chocolate ice-cream": "chocolate_ice-cream",
    "chocolate liqueur": "chocolate_liqueur",
    "chocolate milk": "chocolate_milk",
    "chocolate sauce": "chocolate_sauce",
    "chocolate syrup": "chocolate_syrup",
    "chocolate": "chocolate",
    "cider": "cider",
    "cinnamon schnapps": "cinnamon_schnapps",
    "cinnamon whisky": "cinnamon_whisky",
    "cinnamon": "cinnamon",
    "citrus vodka": "citrus_vodka",
    "clamato juice": "clamato_juice",
    "cloves": "cloves",
    "club soda": "club_soda",
    "coca-cola": "coca-cola",
    "cocchi americano": "cocchi_americano",
    "cocktail onion": "cocktail_onion",
    "cocoa powder": "cocoa_powder",
    "coconut cream": "coconut_cream",
    "coconut liqueur": "coconut_liqueur",
    "coconut milk": "coconut_milk",
    "coconut rum": "coconut_rum",
    "coconut syrup": "coconut_syrup",
    "coffee brandy": "coffee_brandy",
    "coffee liqueur": "coffee_liqueur",
    "coffee": "coffee",
    "cognac": "cognac",
    "cointreau": "cointreau",
    "cola": "cola",
    "cold water": "cold_water",
    "condensed milk": "condensed_milk",
    "coriander": "coriander",
    "corn syrup": "corn_syrup",
    "cornstarch": "cornstarch",
    "corona": "corona",
    "cranberries": "cranberries",
    "cranberry juice": "cranberry_juice",
    "cranberry liqueur": "cranberry_liqueur",
    "cranberry vodka": "cranberry_vodka",
    "cream of coconut": "cream_of_coconut",
    "cream sherry": "cream_sherry",
    "cream soda": "cream_soda",
    "cream": "cream",
    "creme de almond": "creme_de_almond",
    "creme de banane": "creme_de_banane",
    "creme de cacao": "creme_de_cacao",
    "creme de cassis": "creme_de_cassis",
    "creme de mure": "creme_de_mure",
    "creme de noyaux": "creme_de_noyaux",
    "creme de violette": "creme_de_violette",
    "creme fraiche": "creme_fraiche",
    "crown royal": "crown_royal",
    "crystal light": "crystal_light",
    "cucumber": "cucumber",
    "cumin powder": "cumin_powder",
    "cumin seed": "cumin_seed",
    "curacao": "curacao",
    "cynar": "cynar",
    "daiquiri mix": "daiquiri_mix",
    "dark chocolate": "dark_chocolate",
    "dark creme de cacao": "dark_creme_de_cacao",
    "dark rum": "dark_rum",
    "dark soy sauce": "dark_soy_sauce",
    "demerara sugar": "demerara_sugar",
    "diet coke": "diet_coke",
    "dr. pepper": "dr._pepper",
    "drambuie": "drambuie",
    "dried oregano": "dried_oregano",
    "dry curacao": "dry_curacao",
    "dry vermouth": "dry_vermouth",
    "dubonnet blanc": "dubonnet_blanc",
    "dubonnet rouge": "dubonnet_rouge",
    "egg white": "egg_white",
    "egg yolk": "egg_yolk",
    "egg": "egg",
    "eggnog": "eggnog",
    "elderflower cordial": "elderflower_cordial",
    "erin cream": "erin_cream",
    "espresso": "espresso",
    "everclear": "everclear",
    "falernum": "falernum",
    "fanta": "fanta",
    "fennel seeds": "fennel_seeds",
    "fernet-branca": "fernet-branca",
    "figs": "figs",
    "firewater": "firewater",
    "flaked almonds": "flaked_almonds",
    "food coloring": "food_coloring",
    "forbidden fruit": "forbidden_fruit",
    "frangelico": "frangelico",
    "fresca": "fresca",
    "fresh basil": "fresh_basil",
    "fresh lime juice": "fresh_lime_juice",
    "fresh mint": "fresh_mint",
    "fresh lemon juice": "fresh_lemon_juice",
    "fruit juice": "fruit_juice",
    "fruit punch": "fruit_punch",
    "fruit": "fruit",
    "galliano": "galliano",
    "garlic sauce": "garlic_sauce",
    "gatorade": "gatorade",
    "gin": "gin",
    "ginger ale": "ginger_ale",
    "ginger beer": "ginger_beer",
    "ginger syrup": "ginger_syrup",
    "ginger": "ginger",
    "glycerine": "glycerine",
    "godiva liqueur": "godiva_liqueur",
    "gold rum": "gold_rum",
    "gold tequila": "gold_tequila",
    "goldschlager": "goldschlager",
    "grain alcohol": "grain_alcohol",
    "grand marnier": "grand_marnier",
    "granulated sugar": "granulated_sugar",
    "grape juice": "grape_juice",
    "grape soda": "grape_soda",
    "grapefruit juice": "grapefruit_juice",
    "grapes": "grapes",
    "green chartreuse": "green_chartreuse",
    "green creme de menthe": "green_creme_de_menthe",
    "green ginger wine": "green_ginger_wine",
    "green olives": "green_olives",
    "grenadine": "grenadine",
    "ground ginger": "ground_ginger",
    "guava juice": "guava_juice",
    "guinness stout": "guinness_stout",
    "guinness": "guinness",
    "habanero peppers": "habanero_peppers",
    "half-and-half": "half-and-half",
    "hawaiian punch": "hawaiian_punch",
    "hazelnut liqueur": "hazelnut_liqueur",
    "heavy cream": "heavy_cream",
    "honey syrup": "honey_syrup",
    "honey": "honey",
    "hooch": "hooch",
    "hot chocolate": "hot_chocolate",
    "hot damn": "hot_damn",
    "hot sauce": "hot_sauce",
    "hpnotiq": "hpnotiq",
    "ice": "ice",
    "ice-cream": "ice-cream",
    "iced tea": "iced_tea",
    "ilegal joven mezcal": "ilegal_joven_mezcal",
    "irish cream": "irish_cream",
    "irish whiskey": "irish_whiskey",
    "islay single malt scotch": "islay_single_malt_scotch",
    "jack daniels": "jack_daniels",
    "jagermeister": "jagermeister",
    "jello": "jello",
    "jelly": "jelly",
    "jim beam": "jim_beam",
    "johnnie walker": "johnnie_walker",
    "kahlua": "kahlua",
    "key largo schnapps": "key_largo_schnapps",
    "kirschwasser": "kirschwasser",
    "kiwi liqueur": "kiwi_liqueur",
    "kiwi": "kiwi",
    "kool-aid": "kool-aid",
    "kummel": "kummel",
    "lager": "lager",
    "lavender": "lavender",
    "lemon juice": "lemon_juice",
    "lemon peel": "lemon_peel",
    "lemon soda": "lemon_soda",
    "lemon vodka": "lemon_vodka",
    "lemon": "lemon",
    "lemonade": "lemonade",
    "lemon-lime soda": "lemon-lime_soda",
    "lemon-lime": "lemon-lime",
    "licorice root": "licorice_root",
    "light cream": "light_cream",
    "light rum": "light_rum",
    "lillet blanc": "lillet_blanc",
    "lillet": "lillet",
    "lime juice cordial": "lime_juice_cordial",
    "lime juice": "lime_juice",
    "lime liqueur": "lime_liqueur",
    "lime peel": "lime_peel",
    "lime vodka": "lime_vodka",
    "lime": "lime",
    "limeade": "limeade",
    "madeira": "madeira",
    "malibu rum": "malibu_rum",
    "mandarin": "mandarin",
    "mandarine napoleon": "mandarine_napoleon",
    "mango": "mango",
    "maple syrup": "maple_syrup",
    "maraschino cherry juice": "maraschino_cherry_juice",
    "maraschino cherry": "maraschino_cherry",
    "maraschino liqueur": "maraschino_liqueur",
    "margarita mix": "margarita_mix",
    "marjoram leaves": "marjoram_leaves",
    "marshmallows": "marshmallows",
    "martini bianco": "martini_bianco",
    "martini extra dry": "martini_extra_dry",
    "martini rosso": "martini_rosso",
    "maui": "maui",
    "melon liqueur": "melon_liqueur",
    "melon vodka": "melon_vodka",
    "mezcal": "mezcal",
    "midori melon liqueur": "midori_melon_liqueur",
    "midori": "midori",
    "milk": "milk",
    "mini-snickers bars": "mini-snickers_bars",
    "mint syrup": "mint_syrup",
    "mint": "mint",
    "mountain dew": "mountain_dew",
    "nocino": "nocino",
    "nutmeg": "nutmeg",
    "olive brine": "olive_brine",
    "olive oil": "olive_oil",
    "olive": "olive",
    "onion": "onion",
    "orange bitters": "orange_bitters",
    "orange curacao": "orange_curacao",
    "orange juice": "orange_juice",
    "orange liqueur": "orange_liqueur",
    "orange peel": "orange_peel",
    "orange rum": "orange_rum",
    "orange slice": "orange_slice",
    "orange soda": "orange_soda",
    "orange spiral": "orange_spiral",
    "orange vodka": "orange_vodka",
    "orange": "orange",
    "oreo cookie": "oreo_cookie",
    "orgeat syrup": "orgeat_syrup",
    "ouzo": "ouzo",
    "oyster sauce": "oyster_sauce",
    "papaya juice": "papaya_juice",
    "papaya": "papaya",
    "parfait amour": "parfait_amour",
    "passion fruit juice": "passion_fruit_juice",
    "passion fruit syrup": "passion_fruit_syrup",
    "passoa": "passoa",
    "peach bitters": "peach_bitters",
    "peach brandy": "peach_brandy",
    "peach juice": "peach_juice",
    "peach liqueur": "peach_liqueur",
    "peach nectar": "peach_nectar",
    "peach schnapps": "peach_schnapps",
    "peach vodka": "peach_vodka",
    "peach": "peach",
    "peachtree schnapps": "peachtree_schnapps",
    "peanut oil": "peanut_oil",
    "pepper": "pepper",
    "peppermint extract": "peppermint_extract",
    "peppermint schnapps": "peppermint_schnapps",
    "pepsi cola": "pepsi_cola",
    "pernod": "pernod",
    "peychaud bitters": "peychaud_bitters",
    "pina colada mix": "pina_colada_mix",
    "pineapple juice": "pineapple_juice",
    "pineapple rum": "pineapple_rum",
    "pineapple syrup": "pineapple_syrup",
    "pineapple vodka": "pineapple_vodka",
    "pineapple": "pineapple",
    "pineapple-orange-banana juice": "pineapple-orange-banana_juice",
    "pink lemonade": "pink_lemonade",
    "pisang ambon": "pisang_ambon",
    "pisco": "pisco",
    "plain chocolate": "plain_chocolate",
    "plain flour": "plain_flour",
    "plums": "plums",
    "pomegranate juice": "pomegranate_juice",
    "port": "port",
    "powdered sugar": "powdered_sugar",
    "prosecco": "prosecco",
    "purple passion": "purple_passion",
    "raisins": "raisins",
    "ramazzotti": "ramazzotti",
    "raspberry cordial": "raspberry_cordial",
    "raspberry jam": "raspberry_jam",
    "raspberry juice": "raspberry_juice",
    "raspberry liqueur": "raspberry_liqueur",
    "raspberry schnapps": "raspberry_schnapps",
    "raspberry syrup": "raspberry_syrup",
    "raspberry vodka": "raspberry_vodka",
    "red bull": "red_bull",
    "red chile flakes": "red_chile_flakes",
    "red chili flakes": "red_chili_flakes",
    "red hot chili flakes": "red_hot_chili_flakes",
    "red wine": "red_wine",
    "rhubarb": "rhubarb",
    "ricard": "ricard",
    "rock salt": "rock_salt",
    "root beer schnapps": "root_beer_schnapps",
    "root beer": "root_beer",
    "rose": "rose",
    "rosemary syrup": "rosemary_syrup",
    "rosemary": "rosemary",
    "roses sweetened lime juice": "roses_sweetened_lime_juice",
    "rosewater": "rosewater",
    "rosso vermouth": "rosso_vermouth",
    "ruby port": "ruby_port",
    "rum": "rum",
    "rumple minze": "rumple_minze",
    "rye whiskey": "rye_whiskey",
    "sake": "sake",
    "salt": "salt",
    "salted chocolate": "salted_chocolate",
    "sambuca": "sambuca",
    "sarsaparilla": "sarsaparilla",
    "schnapps": "schnapps",
    "schweppes lemon": "schweppes_lemon",
    "schweppes russchian": "schweppes_russchian",
    "scotch": "scotch",
    "sherbet": "sherbet",
    "sherry": "sherry",
    "singani": "singani",
    "sirup of roses": "sirup_of_roses",
    "sloe gin": "sloe_gin",
    "soda water": "soda_water",
    "sour apple pucker": "sour_apple_pucker",
    "sour mix": "sour_mix",
    "southern comfort": "southern_comfort",
    "soy milk": "soy_milk",
    "soy sauce": "soy_sauce",
    "soya milk": "soya_milk",
    "soya sauce": "soya_sauce",
    "spiced rum": "spiced_rum",
    "sprite": "sprite",
    "squeezed orange": "squeezed_orange",
    "squirt": "squirt",
    "st. germain": "st._germain",
    "strawberries": "strawberries",
    "strawberry juice": "strawberry_juice",
    "strawberry liqueur": "strawberry_liqueur",
    "strawberry schnapps": "strawberry_schnapps",
    "strawberry syrup": "strawberry_syrup",
    "sugar syrup": "sugar_syrup",
    "sugar": "sugar",
    "sunny delight": "sunny_delight",
    "surge": "surge",
    "swedish punsch": "swedish_punsch",
    "sweet and sour": "sweet_and_sour",
    "sweet cream": "sweet_cream",
    "sweet vermouth": "sweet_vermouth",
    "tabasco sauce": "tabasco_sauce",
    "tajin": "tajin",
    "tang": "tang",
    "tawny port": "tawny_port",
    "tea": "tea",
    "tennessee whiskey": "tennessee_whiskey",
    "tequila rose": "tequila_rose",
    "tequila": "tequila",
    "thyme": "thyme",
    "tia maria": "tia_maria",
    "tomato juice": "tomato_juice",
    "tomato": "tomato",
    "tonic water": "tonic_water",
    "triple sec": "triple_sec",
    "tropicana": "tropicana",
    "tuaca": "tuaca",
    "vanilla extract": "vanilla_extract",
    "vanilla ice-cream": "vanilla_ice-cream",
    "vanilla liqueur": "vanilla_liqueur",
    "vanilla schnapps": "vanilla_schnapps",
    "vanilla syrup": "vanilla_syrup",
    "vanilla vodka": "vanilla_vodka",
    "vanilla": "vanilla",
    "vermouth": "vermouth",
    "vinegar": "vinegar",
    "vodka": "vodka",
    "water": "water",
    "watermelon schnapps": "watermelon_schnapps",
    "watermelon": "watermelon",
    "whipped cream": "whipped_cream",
    "whipping cream": "whipping_cream",
    "whiskey": "whiskey",
    "whisky": "whisky",
    "white chocolate liqueur": "white_chocolate_liqueur",
    "white creme de menthe": "white_creme_de_menthe",
    "white grape juice": "white_grape_juice",
    "white port": "white_port",
    "white rum": "white_rum",
    "white vermouth": "white_vermouth",
    "white vinegar": "white_vinegar",
    "white wine": "white_wine",
    "wild turkey": "wild_turkey",
    "wildberry schnapps": "wildberry_schnapps",
    "wine": "wine",
    "worcestershire sauce": "worcestershire_sauce",
    "wormwood": "wormwood",
    "yeast": "yeast",
    "yellow chartreuse": "yellow_chartreuse",
    "yoghurt": "yoghurt",
    "yukon jack": "yukon_jack",
    "zima": "zima"
  };

  static String? getImageName(String ingredient) {
    final normalizedIngredient = ingredient.toLowerCase().trim();
    return _imageMap[normalizedIngredient];
  }

  static String? getImagePath(String ingredient) {
    final imageName = getImageName(ingredient);
    return imageName != null
        ? 'assets/data/images/ingredients/$imageName.png'
        : null;
  }

  static bool hasImage(String ingredient) {
    return _imageMap.containsKey(ingredient.toLowerCase().trim());
  }
}
