class IngredientImageMapper {
  static final Map<String, String> _imageMap = {
    "151 proof rum": "151 proof rum",
    "7-up": "7-up",
    "absinthe": "absinthe",
    "absolut citron": "absolut citron",
    "absolut kurant": "absolut kurant",
    "absolut peppar": "absolut peppar",
    "absolut vodka": "absolut vodka",
    "advocaat": "advocaat",
    "aejo rum": "aejo rum",
    "aftershock": "aftershock",
    "agave syrup": "agave syrup",
    "ale": "ale",
    "allspice dram": "allspice dram",
    "allspice": "allspice",
    "almond flavoring": "almond flavoring",
    "almond": "almond",
    "amaretto": "amaretto",
    "amaro montenegro": "amaro montenegro",
    "añejo rum": "añejo rum",
    "angelica root": "angelica root",
    "angostura bitters": "angostura bitters",
    "anis": "anis",
    "anise": "anise",
    "anisette": "anisette",
    "aperol": "aperol",
    "apfelkorn": "apfelkorn",
    "apple brandy": "apple brandy",
    "apple cider": "apple cider",
    "apple juice": "apple juice",
    "apple schnapps": "apple schnapps",
    "apple": "apple",
    "applejack": "applejack",
    "apricot brandy": "apricot brandy",
    "apricot nectar": "apricot nectar",
    "apricot": "apricot",
    "aquavit": "aquavit",
    "arrack": "arrack",
    "asafoetida": "asafoetida",
    "averna": "averna",
    "bacardi limon": "bacardi limon",
    "bacardi": "bacardi",
    "baileys irish cream": "baileys irish cream",
    "banana liqueur": "banana liqueur",
    "banana rum": "banana rum",
    "banana syrup": "banana syrup",
    "banana": "banana",
    "barenjager": "barenjager",
    "basil": "basil",
    "beef stock": "beef stock",
    "beer": "beer",
    "benedictine": "benedictine",
    "berries": "berries",
    "bitter lemon": "bitter lemon",
    "bitters": "bitters",
    "black pepper": "black pepper",
    "black rum": "black rum",
    "black sambuca": "black sambuca",
    "blackberries": "blackberries",
    "blackberry brandy": "blackberry brandy",
    "blackberry schnapps": "blackberry schnapps",
    "blackcurrant cordial": "blackcurrant cordial",
    "blackcurrant schnapps": "blackcurrant schnapps",
    "blackcurrant squash": "blackcurrant squash",
    "blackstrap rum": "blackstrap rum",
    "blended scotch": "blended scotch",
    "blended whiskey": "blended whiskey",
    "blood orange": "blood orange",
    "blue curacao": "blue curacao",
    "blue maui": "blue maui",
    "blueberries": "blueberries",
    "blueberry schnapps": "blueberry schnapps",
    "bourbon": "bourbon",
    "brandy": "brandy",
    "brown sugar": "brown sugar",
    "butter": "butter",
    "butterscotch schnapps": "butterscotch schnapps",
    "cachaca": "cachaca",
    "calvados": "calvados",
    "campari": "campari",
    "canadian whisky": "canadian whisky",
    "candy": "candy",
    "cantaloupe": "cantaloupe",
    "caramel coloring": "caramel coloring",
    "caramel sauce": "caramel sauce",
    "carbonated soft drink": "carbonated soft drink",
    "carbonated water": "carbonated water",
    "cardamom": "cardamom",
    "carrot": "carrot",
    "cayenne pepper": "cayenne pepper",
    "celery salt": "celery salt",
    "celery": "celery",
    "chambord raspberry liqueur": "chambord raspberry liqueur",
    "champagne": "champagne",
    "chareau": "chareau",
    "cherries": "cherries",
    "cherry brandy": "cherry brandy",
    "cherry cola": "cherry cola",
    "cherry grenadine": "cherry grenadine",
    "cherry heering": "cherry heering",
    "cherry juice": "cherry juice",
    "cherry liqueur": "cherry liqueur",
    "cherry": "cherry",
    "chocolate ice-cream": "chocolate ice-cream",
    "chocolate liqueur": "chocolate liqueur",
    "chocolate milk": "chocolate milk",
    "chocolate sauce": "chocolate sauce",
    "chocolate syrup": "chocolate syrup",
    "chocolate": "chocolate",
    "cider": "cider",
    "cinnamon schnapps": "cinnamon schnapps",
    "cinnamon whisky": "cinnamon whisky",
    "cinnamon": "cinnamon",
    "citrus vodka": "citrus vodka",
    "clamato juice": "clamato juice",
    "cloves": "cloves",
    "club soda": "club soda",
    "coca-cola": "coca-cola",
    "cocchi americano": "cocchi americano",
    "cocktail onion": "cocktail onion",
    "cocoa powder": "cocoa powder",
    "coconut cream": "coconut cream",
    "coconut liqueur": "coconut liqueur",
    "coconut milk": "coconut milk",
    "coconut rum": "coconut rum",
    "coconut syrup": "coconut syrup",
    "coffee brandy": "coffee brandy",
    "coffee liqueur": "coffee liqueur",
    "coffee": "coffee",
    "cognac": "cognac",
    "cointreau": "cointreau",
    "cola": "cola",
    "cold water": "cold water",
    "condensed milk": "condensed milk",
    "coriander": "coriander",
    "corn syrup": "corn_syrup",
    "cornstarch": "cornstarch",
    "corona": "corona",
    "cranberries": "cranberries",
    "cranberry juice": "cranberry juice",
    "cranberry liqueur": "cranberry liqueur",
    "cranberry vodka": "cranberry vodka",
    "cream of coconut": "cream of coconut",
    "cream sherry": "cream sherry",
    "cream soda": "cream soda",
    "cream": "cream",
    "creme de almond": "creme de almond",
    "creme de banane": "creme de banane",
    "creme de cacao": "creme de cacao",
    "creme de cassis": "creme de cassis",
    "creme de mure": "creme de mure",
    "creme de noyaux": "creme de noyaux",
    "creme de violette": "creme de violette",
    "creme fraiche": "creme fraiche",
    "crown royal": "crown royal",
    "crystal light": "crystal light",
    "cucumber": "cucumber",
    "cumin powder": "cumin powder",
    "cumin seed": "cumin seed",
    "curacao": "curacao",
    "cynar": "cynar",
    "daiquiri mix": "daiquiri mix",
    "dark chocolate": "dark chocolate",
    "dark creme de cacao": "dark creme de cacao",
    "dark rum": "dark rum",
    "dark soy sauce": "dark soy sauce",
    "demerara sugar": "demerara sugar",
    "diet coke": "diet coke",
    "dr. pepper": "dr._pepper",
    "drambuie": "drambuie",
    "dried oregano": "dried oregano",
    "dry curacao": "dry curacao",
    "dry vermouth": "dry vermouth",
    "dubonnet blanc": "dubonnet blanc",
    "dubonnet rouge": "dubonnet rouge",
    "egg white": "egg white",
    "egg yolk": "egg yolk",
    "egg": "egg",
    "eggnog": "eggnog",
    "elderflower cordial": "elderflower cordial",
    "erin cream": "erin cream",
    "espresso": "espresso",
    "everclear": "everclear",
    "falernum": "falernum",
    "fanta": "fanta",
    "fennel seeds": "fennel seeds",
    "fernet-branca": "fernet-branca",
    "figs": "figs",
    "firewater": "firewater",
    "flaked almonds": "flaked almonds",
    "food coloring": "food coloring",
    "forbidden fruit": "forbidden fruit",
    "frangelico": "frangelico",
    "fresca": "fresca",
    "fresh basil": "fresh basil",
    "fresh lime juice": "fresh lime juice",
    "fresh mint": "fresh mint",
    "fresh lemon juice": "fresh lemon juice",
    "fruit juice": "fruit juice",
    "fruit punch": "fruit punch",
    "fruit": "fruit",
    "galliano": "galliano",
    "garlic sauce": "garlic sauce",
    "gatorade": "gatorade",
    "gin": "gin",
    "ginger ale": "ginger ale",
    "ginger beer": "ginger beer",
    "ginger syrup": "ginger syrup",
    "ginger": "ginger",
    "glycerine": "glycerine",
    "godiva liqueur": "godiva liqueur",
    "gold rum": "gold rum",
    "gold tequila": "gold tequila",
    "goldschlager": "goldschlager",
    "grain alcohol": "grain alcohol",
    "grand marnier": "grand marnier",
    "granulated sugar": "granulated sugar",
    "grape juice": "grape juice",
    "grape soda": "grape soda",
    "grapefruit juice": "grapefruit juice",
    "grapes": "grapes",
    "green chartreuse": "green chartreuse",
    "green creme de menthe": "green creme de menthe",
    "green ginger wine": "green ginger wine",
    "green olives": "green olives",
    "grenadine": "grenadine",
    "ground ginger": "ground ginger",
    "guava juice": "guava juice",
    "guinness stout": "guinness stout",
    "guinness": "guinness",
    "habanero peppers": "habanero peppers",
    "half-and-half": "half-and-half",
    "hawaiian punch": "hawaiian punch",
    "hazelnut liqueur": "hazelnut liqueur",
    "heavy cream": "heavy cream",
    "honey syrup": "honey syrup",
    "honey": "honey",
    "hooch": "hooch",
    "hot chocolate": "hot chocolate",
    "hot damn": "hot damn",
    "hot sauce": "hot sauce",
    "hpnotiq": "hpnotiq",
    "ice": "ice",
    "ice-cream": "ice-cream",
    "iced tea": "iced_tea",
    "ilegal joven mezcal": "ilegal joven mezcal",
    "irish cream": "irish cream",
    "irish whiskey": "irish whiskey",
    "islay single malt scotch": "islay single malt scotch",
    "jack daniels": "jack Daniels",
    "jagermeister": "jagermeister",
    "jello": "jello",
    "jelly": "jelly",
    "jim beam": "jim beam",
    "johnnie walker": "johnnie walker",
    "kahlua": "kahlua",
    "key largo schnapps": "key largo schnapps",
    "kirschwasser": "kirschwasser",
    "kiwi liqueur": "kiwi liqueur",
    "kiwi": "kiwi",
    "kool-aid": "kool-aid",
    "kummel": "kummel",
    "lager": "lager",
    "lavender": "lavender",
    "lemon juice": "lemon juice",
    "lemon peel": "lemon peel",
    "lemon soda": "lemon soda",
    "lemon vodka": "lemon vodka",
    "lemon": "lemon",
    "lemonade": "lemonade",
    "lemon-lime soda": "lemon-lime soda",
    "lemon-lime": "lemon-lime",
    "licorice root": "licorice root",
    "light cream": "light cream",
    "light rum": "light rum",
    "lillet blanc": "lillet blanc",
    "lillet": "lillet",
    "lime juice cordial": "lime juice cordial",
    "lime juice": "lime juice",
    "lime liqueur": "lime liqueur",
    "lime peel": "lime peel",
    "lime vodka": "lime vodka",
    "lime": "lime",
    "limeade": "limeade",
    "madeira": "madeira",
    "malibu rum": "malibu rum",
    "mandarin": "mandarin",
    "mandarine napoleon": "mandarine napoleon",
    "mango": "mango",
    "maple syrup": "maple syrup",
    "maraschino cherry juice": "maraschino cherry juice",
    "maraschino cherry": "maraschino cherry",
    "maraschino liqueur": "maraschino liqueur",
    "margarita mix": "margarita mix",
    "marjoram leaves": "marjoram leaves",
    "marshmallows": "marshmallows",
    "martini bianco": "martini bianco",
    "martini extra dry": "martini extra dry",
    "martini rosso": "martini rosso",
    "maui": "maui",
    "melon liqueur": "melon liqueur",
    "melon vodka": "melon vodka",
    "mezcal": "mezcal",
    "midori melon liqueur": "midori melon liqueur",
    "midori": "midori",
    "milk": "milk",
    "mini-snickers bars": "mini-snickers bars",
    "mint syrup": "mint syrup",
    "mint": "mint",
    "mountain dew": "mountain dew",
    "nocino": "nocino",
    "nutmeg": "nutmeg",
    "olive brine": "olive brine",
    "olive oil": "olive oil",
    "olive": "olive",
    "onion": "onion",
    "orange bitters": "orange bitters",
    "orange curacao": "orange curacao",
    "orange juice": "orange juice",
    "orange liqueur": "orange liqueur",
    "orange peel": "orange peel",
    "orange rum": "orange rum",
    "orange slice": "orange slice",
    "orange soda": "orange soda",
    "orange spiral": "orange spiral",
    "orange vodka": "orange vodka",
    "orange": "orange",
    "oreo cookie": "oreo cookie",
    "orgeat syrup": "orgeat syrup",
    "ouzo": "ouzo",
    "oyster sauce": "oyster sauce",
    "papaya juice": "papaya juice",
    "papaya": "papaya",
    "parfait amour": "parfait amour",
    "passion fruit juice": "passion fruit juice",
    "passion fruit syrup": "passion fruit syrup",
    "passoa": "passoa",
    "peach bitters": "peach_bitters",
    "peach brandy": "peach_brandy",
    "peach juice": "peach juice",
    "peach liqueur": "peach liqueur",
    "peach nectar": "peach_nectar",
    "peach schnapps": "peach_schnapps",
    "peach vodka": "peach_vodka",
    "peach": "peach",
    "peachtree schnapps": "peachtree schnapps",
    "peanut oil": "peanut oil",
    "pepper": "pepper",
    "peppermint extract": "peppermint extract",
    "peppermint schnapps": "peppermint schnapps",
    "pepsi cola": "pepsi cola",
    "pernod": "pernod",
    "peychaud bitters": "peychaud bitters",
    "pina colada mix": "pina colada mix",
    "pineapple juice": "pineapple juice",
    "pineapple rum": "pineapple rum",
    "pineapple syrup": "pineapple syrup",
    "pineapple vodka": "pineapple vodka",
    "pineapple": "pineapple",
    "pineapple-orange-banana juice": "pineapple-orange-banana juice",
    "pink lemonade": "pink lemonade",
    "pisang ambon": "pisang ambon",
    "pisco": "pisco",
    "plain chocolate": "plain chocolate",
    "plain flour": "plain flour",
    "plums": "plums",
    "pomegranate juice": "pomegranate juice",
    "port": "port",
    "powdered sugar": "powdered sugar",
    "prosecco": "prosecco",
    "purple passion": "purple passion",
    "raisins": "raisins",
    "ramazzotti": "ramazzotti",
    "raspberry cordial": "raspberry cordial",
    "raspberry jam": "raspberry jam",
    "raspberry juice": "raspberry juice",
    "raspberry liqueur": "raspberry liqueur",
    "raspberry schnapps": "raspberry schnapps",
    "raspberry syrup": "raspberry syrup",
    "raspberry vodka": "raspberry vodka",
    "red bull": "red bull",
    "red chile flakes": "red chile flakes",
    "red chili flakes": "red chili flakes",
    "red hot chili flakes": "red hot chili flakes",
    "red wine": "red wine",
    "rhubarb": "rhubarb",
    "ricard": "ricard",
    "rock salt": "rock salt",
    "root beer schnapps": "root beer schnapps",
    "root beer": "root beer",
    "rose": "rose",
    "rosemary syrup": "rosemary syrup",
    "rosemary": "rosemary",
    "roses sweetened lime juice": "roses sweetened lime juice",
    "rosewater": "rosewater",
    "rosso vermouth": "rosso vermouth",
    "ruby port": "ruby port",
    "rum": "rum",
    "rumple minze": "rumple minze",
    "rye whiskey": "rye whiskey",
    "sake": "sake",
    "salt": "salt",
    "salted chocolate": "salted chocolate",
    "sambuca": "sambuca",
    "sarsaparilla": "sarsaparilla",
    "schnapps": "schnapps",
    "schweppes lemon": "schweppes lemon",
    "schweppes russchian": "schweppes russchian",
    "scotch": "scotch",
    "sherbet": "sherbet",
    "sherry": "sherry",
    "singani": "singani",
    "sirup of roses": "sirup of roses",
    "sloe gin": "sloe gin",
    "soda water": "soda water",
    "sour apple pucker": "sour apple pucker",
    "sour mix": "sour mix",
    "southern comfort": "southern comfort",
    "soy milk": "soy milk",
    "soy sauce": "soy sauce",
    "soya milk": "soya milk",
    "soya sauce": "soya sauce",
    "spiced rum": "spiced rum",
    "sprite": "sprite",
    "squeezed orange": "squeezed orange",
    "squirt": "squirt",
    "st. germain": "st. germain",
    "strawberries": "strawberries",
    "strawberry juice": "strawberry juice",
    "strawberry liqueur": "strawberry liqueur",
    "strawberry schnapps": "strawberry schnapps",
    "strawberry syrup": "strawberry syrup",
    "sugar syrup": "sugar syrup",
    "sugar": "sugar",
    "sunny delight": "sunny delight",
    "surge": "surge",
    "swedish punsch": "swedish punsch",
    "sweet and sour": "sweet and sour",
    "sweet cream": "sweet cream",
    "sweet vermouth": "sweet vermouth",
    "tabasco sauce": "tabasco sauce",
    "tajin": "tajin",
    "tang": "tang",
    "tawny port": "tawny port",
    "tea": "tea",
    "tennessee whiskey": "tennessee whiskey",
    "tequila rose": "tequila rose",
    "tequila": "tequila",
    "thyme": "thyme",
    "tia maria": "tia maria",
    "tomato juice": "tomato juice",
    "tomato": "tomato",
    "tonic water": "tonic water",
    "triple sec": "triple sec",
    "tropicana": "tropicana",
    "tuaca": "tuaca",
    "vanilla extract": "vanilla extract",
    "vanilla ice-cream": "vanilla ice-cream",
    "vanilla liqueur": "vanilla liqueur",
    "vanilla schnapps": "vanilla schnapps",
    "vanilla syrup": "vanilla syrup",
    "vanilla vodka": "vanilla vodka",
    "vanilla": "vanilla",
    "vermouth": "vermouth",
    "vinegar": "vinegar",
    "vodka": "vodka",
    "water": "water",
    "watermelon schnapps": "watermelon schnapps",
    "watermelon": "watermelon",
    "whipped cream": "whipped cream",
    "whipping cream": "whipping cream",
    "whiskey": "whiskey",
    "whisky": "whisky",
    "white chocolate liqueur": "white chocolate liqueur",
    "white creme de menthe": "white creme de menthe",
    "white grape juice": "white grape juice",
    "white port": "white port",
    "white rum": "white rum",
    "white vermouth": "white vermouth",
    "white vinegar": "white vinegar",
    "white wine": "white wine",
    "wild turkey": "wild turkey",
    "wildberry schnapps": "wildberry schnapps",
    "wine": "wine",
    "worcestershire sauce": "worcestershire sauce",
    "wormwood": "wormwood",
    "yeast": "yeast",
    "yellow chartreuse": "yellow chartreuse",
    "yoghurt": "yoghurt",
    "yukon jack": "yukon jack",
    "zima": "zima"
  };

  static String? getImageName(String ingredient) {
    final normalizedIngredient = ingredient.toLowerCase().trim();
    return _imageMap[normalizedIngredient];
  }

  static String? getImagePath(String ingredient) {
    final imageName = getImageName(ingredient);
    return imageName != null
        ? 'assets/data/images/ingredients/$imageName.png'
        : null;
  }

  static bool hasImage(String ingredient) {
    return _imageMap.containsKey(ingredient.toLowerCase().trim());
  }
}
